service: authorization-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'
useDotenv: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  environment:
    username: ${env:GITHUB_USERNAME}
    password: ${env:TEST_PASSWORD}

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
    url:
      cors: true
    environment: 
      username: ${self:custom.environment.username}
      password: ${self:custom.environment.password}
